In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
index_bool = a > 9
index_bool

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [4]:
a[index_bool]

array([10, 11, 12, 13, 14, 15])

In [5]:
print(a[index_bool])

[10 11 12 13 14 15]


In [6]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [7]:
np.count_nonzero(a < 6)

6

In [8]:
np.sum(a < 6)

6

In [9]:
np.sum(a < 6, axis=1)

array([4, 2, 0, 0])

In [10]:
np.any(a > 8)

True

In [11]:
np.all(a > 8)

False

In [12]:
np.all(a < 50)

True

In [13]:
np.all(a < 9, axis=0)

array([False, False, False, False])

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.all(a < 13, axis=0)

array([ True, False, False, False])