In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 10, 10, 10, 10])

In [3]:
a * b

array([10, 20, 30, 40, 50])

In [4]:
c = 10

In [5]:
a * c

array([10, 20, 30, 40, 50])

In [6]:
ones = np.ones((4, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
ones * c

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [8]:
heights = [165, 170, 168, 183, 172, 169]
weights = [61, 76, 56, 81, 62, 60]

In [9]:
student_bio = np.array([heights, weights])

In [10]:
student_bio

array([[165, 170, 168, 183, 172, 169],
       [ 61,  76,  56,  81,  62,  60]])

In [11]:
factor_1 = np.array([0.0328084, 2.20462])

In [12]:
factor_1.shape

(2,)

In [13]:
student_bio * factor_1

ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

In [14]:
factor_2 = np.array([[0.0328084], [2.20462]])
factor_2

array([[0.0328084],
       [2.20462  ]])

In [16]:
factor_2.shape

(2, 1)

In [17]:
student_bio * factor_2

array([[  5.413386 ,   5.577428 ,   5.5118112,   6.0039372,   5.6430448,
          5.5446196],
       [134.48182  , 167.55112  , 123.45872  , 178.57422  , 136.68644  ,
        132.2772   ]])