In [1]:
import numpy as np

In [2]:
first_array = np.array([1, 2, 3, 4])
first_array

array([1, 2, 3, 4])

In [3]:
numbers = [11, 22, 33, 44, 55, 66]
second_array = np.array(numbers)
second_array

array([11, 22, 33, 44, 55, 66])

In [4]:
type(second_array)

numpy.ndarray

In [6]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
ones_array = np.ones((3, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
ones_array_int = np.ones((4, 5), dtype=np.int16)
ones_array_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [10]:
empty_array = np.empty((2, 3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
eye_array = np.eye(3)
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
eye_array = np.eye(6)
eye_array

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
even_nums = np.arange(4, 20, 2)
even_nums

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
floats_array = np.arange(0, 10, 0.35)
floats_array

array([0.  , 0.35, 0.7 , 1.05, 1.4 , 1.75, 2.1 , 2.45, 2.8 , 3.15, 3.5 ,
       3.85, 4.2 , 4.55, 4.9 , 5.25, 5.6 , 5.95, 6.3 , 6.65, 7.  , 7.35,
       7.7 , 8.05, 8.4 , 8.75, 9.1 , 9.45, 9.8 ])

In [15]:
array_2d = np.array([(2, 4, 6), (3, 5, 7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [16]:
array_2d.shape

(2, 3)

In [17]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
array_nd = np.arange(8).reshape(2, 4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])