In [1]:
import numpy as np

In [2]:
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [3]:
a[0]

0

In [4]:
a[5]

25

In [5]:
a[1]

1

In [6]:
a[-1]

100

In [7]:
a[-5]

36

In [8]:
a[2:5]

array([ 4,  9, 16], dtype=int32)

In [9]:
a[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
a[3:]

array([  9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
a[:8]

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [12]:
a[1:9:3]

array([ 1, 16, 49], dtype=int32)

In [13]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [15]:
students = np.array([["John", "Jack", "Julie", "Joanna"], [59, 78, 89, 99], [15, 84, 54, 32]])
students

array([['John', 'Jack', 'Julie', 'Joanna'],
       ['59', '78', '89', '99'],
       ['15', '84', '54', '32']], dtype='<U11')

In [16]:
students[0]

array(['John', 'Jack', 'Julie', 'Joanna'], dtype='<U11')

In [17]:
students[2]

array(['15', '84', '54', '32'], dtype='<U11')

In [18]:
students[0, 3]

'Joanna'

In [19]:
students[1, 2]

'89'

In [20]:
students[2, 0]

'15'

In [21]:
students[0:2, 0:3]

array([['John', 'Jack', 'Julie'],
       ['59', '78', '89']], dtype='<U11')

In [22]:
students[:, 1:2]

array([['Jack'],
       ['78'],
       ['84']], dtype='<U11')

In [23]:
students[:, 0:3]

array([['John', 'Jack', 'Julie'],
       ['59', '78', '89'],
       ['15', '84', '54']], dtype='<U11')

In [24]:
students[-1, :]

array(['15', '84', '54', '32'], dtype='<U11')

In [25]:
students

array([['John', 'Jack', 'Julie', 'Joanna'],
       ['59', '78', '89', '99'],
       ['15', '84', '54', '32']], dtype='<U11')

In [26]:
students[-3:-1, -2:]

array([['Julie', 'Joanna'],
       ['89', '99']], dtype='<U11')

In [27]:
students[0, ...]

array(['John', 'Jack', 'Julie', 'Joanna'], dtype='<U11')

In [28]:
students[..., 1]

array(['Jack', '78', '84'], dtype='<U11')