In [1]:
import numpy as np

In [2]:
a = np.array([("USA", "Japan", "Turkey", "India"),
              ("Washington, D.C.", "Tokyo", "Ankara", "New Delhi")])
a

array([['USA', 'Japan', 'Turkey', 'India'],
       ['Washington, D.C.', 'Tokyo', 'Ankara', 'New Delhi']], dtype='<U16')

In [3]:
a.shape

(2, 4)

In [4]:
a.ravel()

array(['USA', 'Japan', 'Turkey', 'India', 'Washington, D.C.', 'Tokyo',
       'Ankara', 'New Delhi'], dtype='<U16')

In [5]:
a.T

array([['USA', 'Washington, D.C.'],
       ['Japan', 'Tokyo'],
       ['Turkey', 'Ankara'],
       ['India', 'New Delhi']], dtype='<U16')

In [6]:
a.T.ravel()

array(['USA', 'Washington, D.C.', 'Japan', 'Tokyo', 'Turkey', 'Ankara',
       'India', 'New Delhi'], dtype='<U16')

In [7]:
a.shape

(2, 4)

In [8]:
a.reshape(4, 2)

array([['USA', 'Japan'],
       ['Turkey', 'India'],
       ['Washington, D.C.', 'Tokyo'],
       ['Ankara', 'New Delhi']], dtype='<U16')

In [9]:
np.arange(15).reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
np.arange(15).reshape(15, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [12]:
np.arange(15).reshape(1, 15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [13]:
np.arange(15).reshape(6, 3)

ValueError: cannot reshape array of size 15 into shape (6,3)

In [14]:
np.arange(15).reshape(3, 3)

ValueError: cannot reshape array of size 15 into shape (3,3)

In [15]:
countries = np.array(['USA', 'Japan', 'Turkey', 'India', "Brazil", "Singapore"])
countries

array(['USA', 'Japan', 'Turkey', 'India', 'Brazil', 'Singapore'],
      dtype='<U9')

In [16]:
countries.reshape(-1, 3)

array([['USA', 'Japan', 'Turkey'],
       ['India', 'Brazil', 'Singapore']], dtype='<U9')

In [19]:
countries.reshape(3, -1)

array([['USA', 'Japan'],
       ['Turkey', 'India'],
       ['Brazil', 'Singapore']], dtype='<U9')

In [20]:
countries.reshape(4, -1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)